import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import AppRoot from '../components/approot/AppRoot'

export default function Home({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
          <AppRoot />
      </main>

      
    </div>
  )
}
